{% set version = "1.5.0" %}

package:
  name: asn1crypto
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/asn1crypto/asn1crypto-{{ version }}.tar.gz
  sha256: 2c9eb1b1635425bcadf94749bbcd83bfa8b0a912661bad6106466521d484d62b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - asn1crypto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wbond/asn1crypto
  license: MIT
  license_file: LICENSE
  summary: Python ASN.1 library with a focus on performance and a pythonic API

extra:
  recipe-maintainers:
    - jschueller
    - ocefpaf
